const simbols = {
    'en': [{
            small: 'ё',
            shift: 'Ё',
            code: 'Backquote',
            class: '',
            },
        {
            small: '1',
            shift: '!',
            code: 'Digit1',
            class: '',
        },
        {
            small: '2',
            shift: '"',
            code: 'Digit2',
            class: '',
        },
        {
            small: '3',
            shift: '№',
            code: 'Digit3',
            class: '',
        },
        {
            small: '4',
            shift: ';',
            code: 'Digit4',
            class: '',
        },
        {
            small: '5',
            shift: '%',
            code: 'Digit5',
            class: '',
        },
        {
            small: '6',
            shift: ':',
            code: 'Digit6',
            class: '',
        },
        {
            small: '7',
            shift: '?',
            code: 'Digit7',
            class: '',
        },
        {
            small: '8',
            shift: '*',
            code: 'Digit8',
            class: '',
        },
        {
            small: '9',
            shift: '(',
            code: 'Digit9',
            class: '',
        },
        {
            small: '0',
            shift: ')',
            code: 'Digit0',
            class: '',
        },
        {
            small: '-',
            shift: '_',
            code: 'Minus',
            class: '',
        },
        {
            small: '=',
            shift: '+',
            code: 'Equal',
            class: '',
        },
        {
            small: 'Backspace',
            shift: 'Backspace',
            code: 'Backspace',
            class: 'button__backspace',
        },
        {
            small: 'Tab',
            shift: 'Tab',
            code: 'Tab',
            class: 'button__tab',
        },
        {
            small: 'й',
            shift: 'Й',
            code: 'KeyQ',
            class: '',
        },
        {
            small: 'ц',
            shift: 'Ц',
            code: 'KeyW',
            class: '',
        },
        {
            small: 'у',
            shift: 'У',
            code: 'KeyE',
            class: '',
        },
        {
            small: 'к',
            shift: 'К',
            code: 'KeyR',
            class: '',
        },
        {
            small: 'е',
            shift: 'Е',
            code: 'KeyT',
            class: '',
        },
        {
            small: 'н',
            shift: 'Н',
            code: 'KeyY',
            class: '',
        },
        {
            small: 'г',
            shift: 'Г',
            code: 'KeyU',
            class: '',
        },
        {
            small: 'ш',
            shift: 'Ш',
            code: 'KeyI',
            class: '',
        },
        {
            small: 'щ',
            shift: 'Щ',
            code: 'KeyO',
            class: '',
        },
        {
            small: 'з',
            shift: 'З',
            code: 'KeyP',
            class: '',
        },
        {
            small: 'х',
            shift: 'Х',
            code: 'BracketLeft',
            class: '',
        },
        {
            small: 'ъ',
            shift: 'Ъ',
            code: 'BracketRight',
            class: '',
        },
        {
            small: '\\',
            shift: '|',
            code: 'Backslash',
            class: '',
        },
        {
            small: 'CapsLock',
            shift: 'CapsLock',
            code: 'CapsLock',
            class: 'button__caps',
        },

        {
            small: 'ф',
            shift: 'Ф',
            code: 'KeyA',
            class: '',
        },
        {
            small: 'ы',
            shift: 'Ы',
            code: 'KeyS',
            class: '',
        },
        {
            small: 'в',
            shift: 'В',
            code: 'KeyD',
            class: '',
        },
        {
            small: 'а',
            shift: 'А',
            code: 'KeyF',
            class: '',
        },
        {
            small: 'п',
            shift: 'П',
            code: 'KeyG',
            class: '',
        },
        {
            small: 'р',
            shift: 'Р',
            code: 'KeyH',
            class: '',
        },
        {
            small: 'о',
            shift: 'О',
            code: 'KeyJ',
            class: '',
        },
        {
            small: 'л',
            shift: 'Л',
            code: 'KeyK',
            class: '',
        },
        {
            small: 'д',
            shift: 'Д',
            code: 'KeyL',
            class: '',
        },
        {
            small: 'ж',
            shift: 'Ж',
            code: 'Semicolon',
            class: '',
        },
        {
            small: 'э',
            shift: 'Э',
            code: 'Quote',
            class: '',
        },
        {
            small: 'Enter',
            shift: 'Enter',
            code: 'Enter',
            class: 'button__enter',
        },
        {
            small: 'Shift',
            shift: 'Shift',
            code: 'ShiftLeft',
            class: 'button__shift',
        },
        {
            small: 'я',
            shift: 'Я',
            code: 'KeyZ',
            class: '',
        },
        {
            small: 'ч',
            shift: 'Ч',
            code: 'KeyX',
            class: '',
        },
        {
            small: 'с',
            shift: 'С',
            code: 'KeyC',
            class: '',
        },
        {
            small: 'м',
            shift: 'М',
            code: 'KeyV',
            class: '',
        },
        {
            small: 'и',
            shift: 'И',
            code: 'KeyB',
            class: '',
        },
        {
            small: 'т',
            shift: 'Т',
            code: 'KeyN',
            class: '',
        },
        {
            small: 'ь',
            shift: 'Ь',
            code: 'KeyM',
            class: '',
        },
        {
            small: 'б',
            shift: 'Б',
            code: 'Comma',
            class: '',
        },
        {
            small: 'ю',
            shift: 'Ю',
            code: 'Period',
            class: '',
        },
        {
            small: '.',
            shift: ',',
            code: 'Slash',
            class: '',
        },
        {
            small: '&#9650;',
            shift: '&#9650;',
            code: 'ArrowUp',
            class: '',
        },
        {
            small: 'Shift',
            shift: 'Shift',
            code: 'ShiftRight',
            class: '',
        },
        {
            small: 'Ctrl',
            shift: 'Ctrl',
            code: 'ControlLeft',
            class: 'button__ctrl',
        },
        {
            small: 'Win',
            shift: 'Win',
            code: 'Win',
            class: '',
        },
        {
            small: 'Alt',
            shift: 'Alt',
            code: 'AltLeft',
            class: '',
        },
        {
            small: '&#8212;',
            shift: '&#8212;',
            code: 'Space',
            class: 'button__space',
        },
        {
            small: 'Alt',
            shift: 'Alt',
            code: 'AltRight',
            class: '',
        },
        {
            small: 'Ctrl',
            shift: 'Ctrl',
            code: 'ControlRight',
            class: 'button__ctrl',
        },
        {
            small: '&#9668;',
            shift: '&#9668;',
            code: 'ArrowLeft',
            class: '',
        },

        {
            small: '&#9660;',
            shift: '&#9660;',
            code: 'ArrowDown',
            class: '',
        },
        {
            small: '&#9658;',
            shift: '&#9658;',
            code: 'ArrowRight',
            class: '',
        },
        {
            small: 'Del',
            shift: 'Del',
            code: 'Delete',
            class: '',
        }],
    'ru': [
        {
            small: 'ё',
            shift: 'Ё',
            code: 'Backquote',
            class: '',
        },
        {
            small: '1',
            shift: '!',
            code: 'Digit1',
            class: '',
        },
        {
            small: '2',
            shift: '"',
            code: 'Digit2',
            class: '',
        },
        {
            small: '3',
            shift: '№',
            code: 'Digit3',
            class: '',
        },
        {
            small: '4',
            shift: ';',
            code: 'Digit4',
            class: '',
        },
        {
            small: '5',
            shift: '%',
            code: 'Digit5',
            class: '',
        },
        {
            small: '6',
            shift: ':',
            code: 'Digit6',
            class: '',
        },
        {
            small: '7',
            shift: '?',
            code: 'Digit7',
            class: '',
        },
        {
            small: '8',
            shift: '*',
            code: 'Digit8',
            class: '',
        },
        {
            small: '9',
            shift: '(',
            code: 'Digit9',
            class: '',
        },
        {
            small: '0',
            shift: ')',
            code: 'Digit0',
            class: '',
        },
        {
            small: '-',
            shift: '_',
            code: 'Minus',
            class: '',
        },
        {
            small: '=',
            shift: '+',
            code: 'Equal',
            class: '',
        },
        {
            small: 'Backspace',
            shift: 'Backspace',
            code: 'Backspace',
            class: 'button__backspace',
        },
        {
            small: 'Tab',
            shift: 'Tab',
            code: 'Tab',
            class: 'button__tab',
        },
        {
            small: 'й',
            shift: 'Й',
            code: 'KeyQ',
            class: '',
        },
        {
            small: 'ц',
            shift: 'Ц',
            code: 'KeyW',
            class: '',
        },
        {
            small: 'у',
            shift: 'У',
            code: 'KeyE',
            class: '',
        },
        {
            small: 'к',
            shift: 'К',
            code: 'KeyR',
            class: '',
        },
        {
            small: 'е',
            shift: 'Е',
            code: 'KeyT',
            class: '',
        },
        {
            small: 'н',
            shift: 'Н',
            code: 'KeyY',
            class: '',
        },
        {
            small: 'г',
            shift: 'Г',
            code: 'KeyU',
            class: '',
        },
        {
            small: 'ш',
            shift: 'Ш',
            code: 'KeyI',
            class: '',
        },
        {
            small: 'щ',
            shift: 'Щ',
            code: 'KeyO',
            class: '',
        },
        {
            small: 'з',
            shift: 'З',
            code: 'KeyP',
            class: '',
        },
        {
            small: 'х',
            shift: 'Х',
            code: 'BracketLeft',
            class: '',
        },
        {
            small: 'ъ',
            shift: 'Ъ',
            code: 'BracketRight',
            class: '',
        },
        {
            small: '\\',
            shift: '|',
            code: 'Backslash',
            class: '',
        },
        {
            small: 'Delete',
            shift: 'Delete',
            code: 'Delete',
            class: '',
        },
        {
            small: 'CapsLock',
            shift: 'CapsLock',
            code: 'CapsLock',
            class: 'button__caps',
        },
    
        {
            small: 'ф',
            shift: 'Ф',
            code: 'KeyA',
            class: '',
        },
        {
            small: 'ы',
            shift: 'Ы',
            code: 'KeyS',
            class: '',
        },
        {
            small: 'в',
            shift: 'В',
            code: 'KeyD',
            class: '',
        },
        {
            small: 'а',
            shift: 'А',
            code: 'KeyF',
            class: '',
        },
        {
            small: 'п',
            shift: 'П',
            code: 'KeyG',
            class: '',
        },
        {
            small: 'р',
            shift: 'Р',
            code: 'KeyH',
            class: '',
        },
        {
            small: 'о',
            shift: 'О',
            code: 'KeyJ',
            class: '',
        },
        {
            small: 'л',
            shift: 'Л',
            code: 'KeyK',
            class: '',
        },
        {
            small: 'д',
            shift: 'Д',
            code: 'KeyL',
            class: '',
        },
        {
            small: 'ж',
            shift: 'Ж',
            code: 'Semicolon',
            class: '',
        },
        {
            small: 'э',
            shift: 'Э',
            code: 'Quote',
            class: '',
        },
        {
            small: 'Enter',
            shift: 'Enter',
            code: 'Enter',
            class: 'button__enter',
        },
        {
            small: 'Shift',
            shift: 'Shift',
            code: 'ShiftLeft',
            class: 'button__shift',
        },
        {
            small: '/',
            shift: '|',
            code: 'IntlBackslash',
            class: '',
        },
        {
            small: 'я',
            shift: 'Я',
            code: 'KeyZ',
            class: '',
        },
        {
            small: 'ч',
            shift: 'Ч',
            code: 'KeyX',
            class: '',
        },
        {
            small: 'с',
            shift: 'С',
            code: 'KeyC',
            class: '',
        },
        {
            small: 'м',
            shift: 'М',
            code: 'KeyV',
            class: '',
        },
        {
            small: 'и',
            shift: 'И',
            code: 'KeyB',
            class: '',
        },
        {
            small: 'т',
            shift: 'Т',
            code: 'KeyN',
            class: '',
        },
        {
            small: 'ь',
            shift: 'Ь',
            code: 'KeyM',
            class: '',
        },
        {
            small: 'б',
            shift: 'Б',
            code: 'Comma',
            class: '',
        },
        {
            small: 'ю',
            shift: 'Ю',
            code: 'Period',
            class: '',
        },
        {
            small: '.',
            shift: ',',
            code: 'Slash',
            class: '',
        },
        {
            small: '&#9650;',
            shift: '&#9650;',
            code: 'ArrowUp',
            class: '',
        },
        {
            small: 'Shift',
            shift: 'Shift',
            code: 'ShiftRight',
            class: '',
        },
        {
            small: 'Ctrl',
            shift: 'Ctrl',
            code: 'ControlLeft',
            class: 'button__ctrl',
        },
        {
            small: 'RU',
            shift: 'RU',
            code: 'lang',
            class: '',
        },
        {
            small: 'Alt',
            shift: 'Alt',
            code: 'AltLeft',
            class: '',
        },
        {
            small: '&#8212;',
            shift: '&#8212;',
            code: 'Space',
            class: 'button__space',
        },
        {
            small: 'Alt',
            shift: 'Alt',
            code: 'AltRight',
            class: '',
        },
        {
            small: 'Ctrl',
            shift: 'Ctrl',
            code: 'ControlRight',
            class: 'button__ctrl',
        },
        {
            small: '&#9668;',
            shift: '&#9668;',
            code: 'ArrowLeft',
            class: '',
        },
    
        {
            small: '&#9660;',
            shift: '&#9660;',
            code: 'ArrowDown',
            class: '',
        },
        {
            small: '&#9658;',
            shift: '&#9658;',
            code: 'ArrowRight',
            class: '',
        },
    ]
};

export default simbols;