const simbols = {
    'en': [
        {
            key: '`',
            shift: '~',
            code: 'Backquote',
            class: '',
        },
        {
            key: '1',
            shift: '!',
            code: 'Digit1',
            class: '',
        },
        {
            key: '2',
            shift: '@',
            code: 'Digit2',
            class: '',
        },
        {
            key: '3',
            shift: '#',
            code: 'Digit3',
            class: '',
        },
        {
            key: '4',
            shift: '$',
            code: 'Digit4',
            class: '',
        },
        {
            key: '5',
            shift: '%',
            code: 'Digit5',
            class: '',
        },
        {
            key: '6',
            shift: '^',
            code: 'Digit6',
            class: '',
        },
        {
            key: '7',
            shift: '&',
            code: 'Digit7',
            class: '',
        },
        {
            key: '8',
            shift: '*',
            code: 'Digit8',
            class: '',
        },
        {
            key: '9',
            shift: '(',
            code: 'Digit9',
            class: '',
        },
        {
            key: '0',
            shift: ')',
            code: 'Digit0',
            class: '',
        },
        {
            key: '-',
            shift: '_',
            code: 'Minus',
            class: '',
        },
        {
            key: '=',
            shift: '+',
            code: 'Equal',
            class: '',
        },
        {
            key: 'Backspace',
            shift: 'Backspace',
            code: 'Backspace',
            class: 'button__backspace',
        },
        {
            key: 'Tab',
            shift: 'Tab',
            code: 'Tab',
            class: 'button__tab',
        },
        {
            key: 'q',
            shift: 'Q',
            code: 'KeyQ',
            class: '',
        },
        {
            key: 'w',
            shift: 'W',
            code: 'KeyW',
            class: '',
        },
        {
            key: 'e',
            shift: 'E',
            code: 'KeyE',
            class: '',
        },
        {
            key: 'r',
            shift: 'R',
            code: 'KeyR',
            class: '',
        },
        {
            key: 't',
            shift: 'T',
            code: 'KeyT',
            class: '',
        },
        {
            key: 'y',
            shift: 'Y',
            code: 'KeyY',
            class: '',
        },
        {
            key: 'u',
            shift: 'U',
            code: 'KeyU',
            class: '',
        },
        {
            key: 'i',
            shift: 'I',
            code: 'KeyI',
            class: '',
        },
        {
            key: 'o',
            shift: 'O',
            code: 'KeyO',
            class: '',
        },
        {
            key: 'p',
            shift: 'P',
            code: 'KeyP',
            class: '',
        },
        {
            key: '[',
            shift: '{',
            code: 'BracketLeft',
            class: '',
        },
        {
            key: ']',
            shift: '}',
            code: 'BracketRight',
            class: '',
        },
        {
            key: '\\',
            shift: '|',
            code: 'Backslash',
            class: '',
        },         
        {
            key: 'CapsLock',
            shift: 'CapsLock',
            code: 'CapsLock',
            class: 'button__caps',
        },
        {
            key: 'a',
            shift: 'A',
            code: 'KeyA',
            class: '',
        },
        {
            key: 's',
            shift: 'S',
            code: 'KeyS',
            class: '',
        },
        {
            key: 'd',
            shift: 'D',
            code: 'KeyD',
            class: '',
        },
        {
            key: 'f',
            shift: 'F',
            code: 'KeyF',
            class: '',
        },
        {
            key: 'g',
            shift: 'G',
            code: 'KeyG',
            class: '',
        },
        {
            key: 'h',
            shift: 'H',
            code: 'KeyH',
            class: '',
        },
        {
            key: 'j',
            shift: 'J',
            code: 'KeyJ',
            class: '',
        },
        {
            key: 'k',
            shift: 'K',
            code: 'KeyK',
            class: '',
        },
        {
            key: 'l',
            shift: 'L',
            code: 'KeyL',
            class: '',
        },
        {
            key: ';',
            shift: ':',
            code: 'Semicolon',
            class: '',
        },
        {
            key: "'",
            shift: '"',
            code: 'Quote',
            class: '',
        },
    
        {
            key: 'Enter',
            shift: 'Enter',
            code: 'Enter',
            class: 'button__enter',
        },
        {
            key: 'Shift',
            shift: 'Shift',
            code: 'ShiftLeft',
            class: 'button__shift',
        },
        {
            key: 'z',
            shift: 'Z',
            code: 'KeyZ',
            class: '',
        },
        {
            key: 'x',
            shift: 'X',
            code: 'KeyX',
            class: '',
        },
        {
            key: 'c',
            shift: 'C',
            code: 'KeyC',
            class: '',
        },
        {
            key: 'v',
            shift: 'V',
            code: 'KeyV',
            class: '',
        },
        {
            key: 'b',
            shift: 'B',
            code: 'KeyB',
            class: '',
        },
        {
            key: 'n',
            shift: 'N',
            code: 'KeyN',
            class: '',
        },
        {
            key: 'm',
            shift: 'M',
            code: 'KeyM',
            class: '',
        },
        {
            key: ',',
            shift: '<',
            code: 'Comma',
            class: '',
        },
        {
            key: '.',
            shift: '>',
            code: 'Period',
            class: '',
        },
        {
            key: '/',
            shift: '?',
            code: 'Slash',
            class: '',
        },
        {
            key: '&#9650;',
            shift: '&#9650;',
            code: 'ArrowUp',
            class: '',
        },
        {
            key: 'Shift',
            shift: 'Shift',
            code: 'ShiftRight',
            class: '',
        },
        {
            key: 'Ctrl',
            shift: 'Ctrl',
            code: 'ControlLeft',
            class: 'button__ctrl',
        },
        {
            key: 'Win',
            shift: 'Win',
            code: 'Win',
            class: '',
        },
        {
            key: 'Alt',
            shift: 'Alt',
            code: 'AltLeft',
            class: '',
        },
        {
            key: '&#8212;',
            shift: '&#8212;',
            code: 'Space',
            class: 'button__space',
        },
        {
            key: 'Alt',
            shift: 'Alt',
            code: 'AltRight',
            class: '',
        },
        {
            key: 'Ctrl',
            shift: 'Ctrl',
            code: 'ControlRight',
            class: 'button__ctrl',
        },
        {
            key: '&#9668;',
            shift: '&#9668;',
            code: 'ArrowLeft',
            class: '',
        },
    
        {
            key: '&#9660;',
            shift: '&#9660;',
            code: 'ArrowDown',
            class: '',
        },
        {
            key: '&#9658;',
            shift: '&#9658;',
            code: 'ArrowRight',
            class: '',
        },
        {
            key: 'Del',
            shift: 'Del',
            code: 'Delete',
            class: '',
        },
    ],
    'ru': [
        {
            key: 'ё',
            shift: 'Ё',
            code: 'Backquote',
            class: '',
        },
        {
            key: '1',
            shift: '!',
            code: 'Digit1',
            class: '',
        },
        {
            key: '2',
            shift: '"',
            code: 'Digit2',
            class: '',
        },
        {
            key: '3',
            shift: '№',
            code: 'Digit3',
            class: '',
        },
        {
            key: '4',
            shift: ';',
            code: 'Digit4',
            class: '',
        },
        {
            key: '5',
            shift: '%',
            code: 'Digit5',
            class: '',
        },
        {
            key: '6',
            shift: ':',
            code: 'Digit6',
            class: '',
        },
        {
            key: '7',
            shift: '?',
            code: 'Digit7',
            class: '',
        },
        {
            key: '8',
            shift: '*',
            code: 'Digit8',
            class: '',
        },
        {
            key: '9',
            shift: '(',
            code: 'Digit9',
            class: '',
        },
        {
            key: '0',
            shift: ')',
            code: 'Digit0',
            class: '',
        },
        {
            key: '-',
            shift: '_',
            code: 'Minus',
            class: '',
        },
        {
            key: '=',
            shift: '+',
            code: 'Equal',
            class: '',
        },
        {
            key: 'Backspace',
            shift: 'Backspace',
            code: 'Backspace',
            class: 'button__backspace',
        },
        {
            key: 'Tab',
            shift: 'Tab',
            code: 'Tab',
            class: 'button__tab',
        },
        {
            key: 'й',
            shift: 'Й',
            code: 'KeyQ',
            class: '',
        },
        {
            key: 'ц',
            shift: 'Ц',
            code: 'KeyW',
            class: '',
        },
        {
            key: 'у',
            shift: 'У',
            code: 'KeyE',
            class: '',
        },
        {
            key: 'к',
            shift: 'К',
            code: 'KeyR',
            class: '',
        },
        {
            key: 'е',
            shift: 'Е',
            code: 'KeyT',
            class: '',
        },
        {
            key: 'н',
            shift: 'Н',
            code: 'KeyY',
            class: '',
        },
        {
            key: 'г',
            shift: 'Г',
            code: 'KeyU',
            class: '',
        },
        {
            key: 'ш',
            shift: 'Ш',
            code: 'KeyI',
            class: '',
        },
        {
            key: 'щ',
            shift: 'Щ',
            code: 'KeyO',
            class: '',
        },
        {
            key: 'з',
            shift: 'З',
            code: 'KeyP',
            class: '',
        },
        {
            key: 'х',
            shift: 'Х',
            code: 'BracketLeft',
            class: '',
        },
        {
            key: 'ъ',
            shift: 'Ъ',
            code: 'BracketRight',
            class: '',
        },
        {
            key: '\\',
            shift: '|',
            code: 'Backslash',
            class: '',
        },
        {
            key: 'CapsLock',
            shift: 'CapsLock',
            code: 'CapsLock',
            class: 'button__caps',
        },
    
        {
            key: 'ф',
            shift: 'Ф',
            code: 'KeyA',
            class: '',
        },
        {
            key: 'ы',
            shift: 'Ы',
            code: 'KeyS',
            class: '',
        },
        {
            key: 'в',
            shift: 'В',
            code: 'KeyD',
            class: '',
        },
        {
            key: 'а',
            shift: 'А',
            code: 'KeyF',
            class: '',
        },
        {
            key: 'п',
            shift: 'П',
            code: 'KeyG',
            class: '',
        },
        {
            key: 'р',
            shift: 'Р',
            code: 'KeyH',
            class: '',
        },
        {
            key: 'о',
            shift: 'О',
            code: 'KeyJ',
            class: '',
        },
        {
            key: 'л',
            shift: 'Л',
            code: 'KeyK',
            class: '',
        },
        {
            key: 'д',
            shift: 'Д',
            code: 'KeyL',
            class: '',
        },
        {
            key: 'ж',
            shift: 'Ж',
            code: 'Semicolon',
            class: '',
        },
        {
            key: 'э',
            shift: 'Э',
            code: 'Quote',
            class: '',
        },
        {
            key: 'Enter',
            shift: 'Enter',
            code: 'Enter',
            class: 'button__enter',
        },
        {
            key: 'Shift',
            shift: 'Shift',
            code: 'ShiftLeft',
            class: 'button__shift',
        },
        {
            key: 'я',
            shift: 'Я',
            code: 'KeyZ',
            class: '',
        },
        {
            key: 'ч',
            shift: 'Ч',
            code: 'KeyX',
            class: '',
        },
        {
            key: 'с',
            shift: 'С',
            code: 'KeyC',
            class: '',
        },
        {
            key: 'м',
            shift: 'М',
            code: 'KeyV',
            class: '',
        },
        {
            key: 'и',
            shift: 'И',
            code: 'KeyB',
            class: '',
        },
        {
            key: 'т',
            shift: 'Т',
            code: 'KeyN',
            class: '',
        },
        {
            key: 'ь',
            shift: 'Ь',
            code: 'KeyM',
            class: '',
        },
        {
            key: 'б',
            shift: 'Б',
            code: 'Comma',
            class: '',
        },
        {
            key: 'ю',
            shift: 'Ю',
            code: 'Period',
            class: '',
        },
        {
            key: '.',
            shift: ',',
            code: 'Slash',
            class: '',
        },
        {
            key: '&#9650;',
            shift: '&#9650;',
            code: 'ArrowUp',
            class: '',
        },
        {
            key: 'Shift',
            shift: 'Shift',
            code: 'ShiftRight',
            class: '',
        },
        {
            key: 'Ctrl',
            shift: 'Ctrl',
            code: 'ControlLeft',
            class: 'button__ctrl',
        },
        {
            key: 'Win',
            shift: 'Win',
            code: 'Win',
            class: '',
        },
        {
            key: 'Alt',
            shift: 'Alt',
            code: 'AltLeft',
            class: '',
        },
        {
            key: '&#8212;',
            shift: '&#8212;',
            code: 'Space',
            class: 'button__space',
        },
        {
            key: 'Alt',
            shift: 'Alt',
            code: 'AltRight',
            class: '',
        },
        {
            key: 'Ctrl',
            shift: 'Ctrl',
            code: 'ControlRight',
            class: 'button__ctrl',
        },
        {
            key: '&#9668;',
            shift: '&#9668;',
            code: 'ArrowLeft',
            class: '',
        },
    
        {
            key: '&#9660;',
            shift: '&#9660;',
            code: 'ArrowDown',
            class: '',
        },
        {
            key: '&#9658;',
            shift: '&#9658;',
            code: 'ArrowRight',
            class: '',
        },
        {
            key: 'Del',
            shift: 'Del',
            code: 'Delete',
            class: '',
        }
    ]
};

export default simbols;